<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CRN.Domain\CRN.Domain.csproj" />
    <ProjectReference Include="..\CRN.Infrastructure\CRN.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.0" />
  </ItemGroup>

</Project>
