<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<PreserveCompilationContext>true</PreserveCompilationContext>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.19" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />

		<PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />

		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.0" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\CRN.Application\CRN.Application.csproj" />
		<ProjectReference Include="..\CRN.Infrastructure\CRN.Infrastructure.csproj" />
	</ItemGroup>


	<ItemGroup>
		<Folder Include="Extensions\" />
		<Folder Include="Filters\" />
	</ItemGroup>

</Project>